# Generated by Django 4.0.4 on 2022-12-08 20:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


def alter_table_person(migrations):
    return [
        migrations.RunSQL(
            sql=f'ALTER TABLE content.person ALTER COLUMN {field} '
                'SET DEFAULT NOW();',
            reverse_sql='',
        )
        for field in ('created', 'modified')
    ]


def alter_table_film_work(migrations):
    return [
        migrations.RunSQL(
            sql=f'ALTER TABLE content.film_work ALTER COLUMN {field} '
                'SET DEFAULT NOW();',
            reverse_sql='',
        )
        for field in ('created', 'modified', 'creation_date')
    ]


def alter_table_genre(migrations):
    return [
        migrations.RunSQL(
            sql=f'ALTER TABLE content.genre ALTER COLUMN {field} '
                'SET DEFAULT NOW();',
            reverse_sql='',
        )
        for field in ('created', 'modified')
    ]


def alter_table_genre_film_work(migrations):
    return [
        migrations.RunSQL(
            sql=f'ALTER TABLE content.genre_film_work ALTER COLUMN {field} '
                'SET DEFAULT NOW();',
            reverse_sql='',
        )
        for field in ('created',)
    ]


def alter_text_field(migrations):
    return [
        migrations.RunSQL(
            sql=(f"ALTER TABLE content.{table} ALTER COLUMN "
                 "description DROP NOT NULL;"),
            reverse_sql='',
        )
        for table in ('film_work', 'genre')
    ]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS content;"),
        migrations.CreateModel(
            name='Filmwork',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('creation_date', models.DateField(auto_now=True, null=True)),
                ('rating', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='rating')),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'Tv_show')], max_length=10, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Кинопроизведение',
                'verbose_name_plural': 'Кинопроизведения',
                'db_table': 'content"."film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(default='description this genre coming soon.', verbose_name='description')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'content"."genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='full_name')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажы',
                'db_table': 'content"."person',
            },
        ),
        migrations.CreateModel(
            name='ProgressTransferData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('id_row', models.UUIDField()),
                ('count_row', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Прогресс переноса данных',
                'db_table': 'content"."progress_transfer_data',
            },
        ),
        migrations.CreateModel(
            name='PersonFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.TextField(choices=[('actor', 'actor'), ('director', 'director'), ('writer', 'writer')], verbose_name='role')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
            options={
                'db_table': 'content"."person_film_work',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='filmworks',
            field=models.ManyToManyField(through='movies.PersonFilmwork', to='movies.filmwork'),
        ),
        migrations.CreateModel(
            name='GenreFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
            ],
            options={
                'db_table': 'content"."genre_film_work',
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(through='movies.GenreFilmwork', to='movies.genre'),
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(fields=('film_work_id', 'person_id', 'role'), name='film_work_person_idx'),
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(fields=('film_work_id', 'genre_id'), name='genre_film_work_idx'),
        ),
        *alter_table_person(migrations),
        *alter_table_genre(migrations),
        *alter_table_film_work(migrations),
        *alter_table_genre_film_work(migrations),
        *alter_text_field(migrations),
        migrations.RunSQL(
            sql=("CREATE TYPE role_enum AS ENUM ('actor', 'writer', 'director');"
                 "ALTER TABLE content.person_film_work ALTER COLUMN role TYPE role_enum USING role::role_enum"),
            reverse_sql='',
        ),
    ]
